//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_Service_Auto.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Angajat()
        {
            this.Interventie_Serviciu = new HashSet<Interventie_Serviciu>();
        }
    
        public int id_angajat { get; set; }
        public string nume { get; set; }
        public string CNP { get; set; }
        public string serieCI { get; set; }
        public Nullable<int> numarCI { get; set; }
        public Nullable<System.DateTime> data_nasterii { get; set; }
        public Nullable<System.DateTime> data_angajare { get; set; }
        public string adresa { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public Nullable<double> salariu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interventie_Serviciu> Interventie_Serviciu { get; set; }
    }
}
