//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_Service_Auto.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AplicatieServiceAutoEntities : DbContext
    {
        public AplicatieServiceAutoEntities()
            : base("name=AplicatieServiceAutoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Angajat> Angajat { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Interventie> Interventie { get; set; }
        public virtual DbSet<Interventie_Serviciu> Interventie_Serviciu { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Masina> Masina { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Serviciu> Serviciu { get; set; }
    }
}
