//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_Service_Auto.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interventie_Serviciu
    {
        public int id_int_serv { get; set; }
        public Nullable<int> id_interventie { get; set; }
        public Nullable<int> id_serviciu { get; set; }
        public Nullable<int> id_angajat { get; set; }
        public Nullable<double> pret { get; set; }
    
        public virtual Angajat Angajat { get; set; }
        public virtual Interventie Interventie { get; set; }
        public virtual Serviciu Serviciu { get; set; }
    }
}
