//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_Service_Auto.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interventie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interventie()
        {
            this.Interventie_Serviciu = new HashSet<Interventie_Serviciu>();
        }
    
        public int id_interventie { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_masina { get; set; }
        public Nullable<System.DateTime> data_primire { get; set; }
        public Nullable<System.DateTime> data_finalizare { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interventie_Serviciu> Interventie_Serviciu { get; set; }
        public virtual Masina Masina { get; set; }
    }
}
