//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_Service_Auto.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masina()
        {
            this.Interventie = new HashSet<Interventie>();
        }
    
        public int id_masina { get; set; }
        public Nullable<int> id_client { get; set; }
        public string serie_sasiu { get; set; }
        public string nr_inmatriculare { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_model { get; set; }
        public Nullable<int> rulaj { get; set; }
        public Nullable<int> an_fabricatie { get; set; }
        public string motorizare { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interventie> Interventie { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Model Model { get; set; }
    }
}
